config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'sessions#top'

  resources :likes, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :contacts
  resources :users
  resources :posts do
    resources :comments

    collection do
    post :confirm
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :wifis
  has_many :toilets
  has_many :troubles


  accepts_nested_attributes_for :wifis
  accepts_nested_attributes_for :toilets
  accepts_nested_attributes_for :troubles


  validates :content, presence: true
  validates :content,length:{maximum:500}
  validates :spot, presence: true
  mount_uploader :image, ImageUploader
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :post,optional: true

end

app/models/trouble.rb
class Trouble < ApplicationRecord
  belongs_to :post,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, uniqueness: true
  validates :email, uniqueness: true
  mount_uploader :image, ImageUploader

end

app/models/wifi.rb
class Wifi < ApplicationRecord
  belongs_to :post,optional: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to post_path(@post), notice: '投稿できませんでした' }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    render :index if @comment.destroy
  end

  def comment_params
    params.require(:comment).permit(
      :post_id,
      :user_id,
      :content,
      :image,
      :image_cache,
      :wifi,
      :toilet,
      :trouble
    )
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]


def create
  like = current_user.likes.create(post_id: params[:post_id])
  redirect_to posts_path, notice: "お気に入りしました"
end


def destroy
  like = current_user.likes.find_by(post_id: params[:post_id]).destroy
  redirect_to post_path, notice: "お気に入りを取り消しました"
end

private

def logged_in_user
  unless current_user
    flash[:referer] = 'ログインしてください'
    render new_session_path
  end
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new,:edit,:show]

  def index
    @posts = Post.all
    @search = Post.search(params[:q])
    @posts = @search.result
  end

  def new
    if params[:back]
      @post = Post.new(post_params)

    else
      @post = Post.new
      @post.wifis.build
      @post.toilets.build
      @post.troubles.build
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        ContactMailer.post_mail(@post).deliver_later
        format.html { redirect_to @post, notice: '投稿しました' }
        format.json { render :show, status: :created, location: @post }

      else
        render 'new'
      end
    end

  end

  def show
    @comment = @post.comments.build
    @comments = @post.comments
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to posts_path, notice: '編集しました！'
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '削除しました！'
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    render :new if @post.invalid?
  end

  private

  def post_params
    params.require(:post).permit(
      :content,
      :user_id,
      :image,
      :cache,
      :image_cach,
      :spot,
      wifis_attributes: [:condition_1, :condition_2, :condition_3 ],
      toilets_attributes: [:information, :comfortable, :box_number, :baggage ],
      troubles_attributes: [:atm, :station, :bus, :pharmacy ]
    )
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def logged_in_user
    unless current_user
      flash[:referer] = 'ログインしてください'
      render new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録完了しました"
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @likes_posts = @user.like_posts
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
       redirect_to @user, notice: '編集しました！'
    else
      render 'edit'
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :image,
        :area,
        :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_posts_path

    elsif action_name == 'edit'
      post_path
    end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user) #userを渡す
    session[:user_id] = user.id
  end

  def current_user #ログイン中のuserがいる場合
    @current_user ||= User.find_by(id: session[:user_id]) #userが存在しない場合falseを返す
  end

  def logged_in? #ログインしていればtrueを返す
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/toilets_helper.rb
module ToiletsHelper
end

app/helpers/troubles_helper.rb
module TroublesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wifis_helper.rb
module WifisHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |form| %>
<% if comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(comment.errors.count, "error") %>
      prohibited this comment from being saved:</h2>
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form.text_area :content ,class: "form-control" ,placeholder: "この投稿へのコメント"%>
<br>
<%= form.file_field :image, id: :feed_image %>
<%= form.hidden_field :image_cache %>
<br>
<%= form.text_area :wifi ,class: "form-control" ,placeholder: "wifi情報について"%>
<br>
<%= form.text_area :toilet ,class: "form-control" ,placeholder: "toilet情報について"%>
<br>
<%= form.text_area :trouble ,class: "form-control" ,placeholder: "help情報について"%>
<br>
<%= form.submit "登録する" , class: 'col-xs-offset-4 col-xs-4 btn btn-danger'%>
<% end %>

app/views/comments/_index.html.erb
<p class="comment"><%= comments.count %>件のコメント</p>
<hr>
<% comments.each do |comment| %>

  <% unless comment.id.nil? %>

    <p><%= image_tag(post.user.image , size: 30) %>
      <%= comment.user.name %></p>

    <p>
      <i class="fa far fa-comment fa-fw fa-1x"></i>
      <%= comment.content %></p>
    <p>
      <i class="fa fas fa-wifi fa-fw fa-1x"></i>
      <%= comment.wifi %></p>
    <p>
      <i class="fa fas fa-female fa-fw fa-1x"></i>
      <%= comment.toilet %></p>
    <p>
      <i class="fa fas fa-medkit fa-fw fa-1x"></i>
      <%= comment.trouble %></p>

    <% if comment.image.present? %>
      <%= image_tag(comment.image , size: 100) %>
    <% end %>

    <div class="col-md-5 col-md-offset-7 text-right">
      <% if comment.user == current_user %>
        <%= link_to "",post_comment_path(comment.post_id, comment.id), method: :delete, remote: true ,class: 'fa fas fa-trash fa-fw fa-2x'%>
      <% end %>
    </div>
    <br>
    <hr>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.post.comments, post: @comment.post }) %>")
$("textarea").val('')

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true,url: choose_new_or_edit ) do |form| %>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= @post.errors.count %>件のエラーがあります</h2>

    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 ">

      <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
          <h1>
            <i class="fa fa-dribbble fa-fw fa-2x"></i>
            <strong>spot</strong>
          </h1>
          <%= form.text_field :spot ,class: "form-control" ,placeholder: "どこへ行きましたか？(必須）"%>
        </div>
        <br>
        <br>

        <div class="form-group col-xs-12 floating-label-form-group controls">
          <h1>
            <i class="fa fa-camera fa-fw fa-2x"></i>
            <strong>picture</strong>
          </h1>
          <%= form.file_field :image, id: :feed_image ,placeholder: "pic"%>
          <%= form.hidden_field :image_cache %>
        </div>
        <br>
        <br>

        <div class="form-group col-xs-12 floating-label-form-group controls">
          <h1>
            <i class="fa fas fa-comment fa-fw fa-2x"></i>
            <strong>how about this spot?</strong>
          </h1>
          <%= form.text_field :content ,class: "form-control" ,placeholder: "行ってみてどうでしたか？（必須）"%>
        </div>
        <br>
        <br>
      </div>
      <hr>

      <!-- wifi -->
      <%= render partial: 'wifi', locals: {form: form} %>

      <!-- トイレ -->
      <%= render partial: 'toilet', locals: {form: form} %>

      <!--トラブル-->
      <%= render partial: 'trouble', locals: {form: form} %>

      <%= form.submit "登録する", class: 'col-xs-offset-4 col-xs-4 btn btn-danger btn-lg' %>
      <br>
    <% end %>
    <br>
    <br>
    <%= link_to "一覧画面へ戻る", posts_path, class: 'col-xs-offset-4 col-xs-4 btn btn-dark btn-lg' %>

  </div>
</div>
</div>
</div>

app/views/posts/_toilet.html.erb
<div class="row control-group">

  <%= form.fields_for :toilets do |t| %>

  <div class="form-group col-xs-12 floating-label-form-group controls">
    <h1>
      <i class="fa fas fa-female fa-fw fa-2x"></i>
      <strong>toilet情報</strong>
    </h1>

    <p class="lead">清潔ですか？
      <%= t.text_field :comfortable ,class: "form-control" ,placeholder: "快適度"%>
    </p>
    <br>
  </div>

  <div class="form-group col-xs-12 floating-label-form-group controls">
    <p class="lead">個室はいくつありますか？
      <%= t.text_field :box_number,class: "form-control" ,placeholder: "個室の数"%>
    </p>
    <br>
  </div>

  <div class="form-group col-xs-12 floating-label-form-group controls">
    <p class="lead">荷物置き場はありますか？
      <%= t.text_field :baggage,class: "form-control" ,placeholder: "荷物スペース"%>
    </p>
    <br>
  </div>

  <div class="form-group col-xs-12 floating-label-form-group controls">
    <p class="lead">コメントがあれば記入してください
      <%= t.text_field :information,class: "form-control" ,placeholder: "その他"%>
    </p>
  </div>

<% end %>
<br>
<br>
</div>
<hr>

app/views/posts/confirm.html.erb
<aside class="callout">
  <div class="text-vertical-center">
    <h1>Are you OK?</h1>
  </div>
</aside>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

      <h1>
        <i class="fa far fa-check-circle fa-fw fa-2x"></i>
        <strong>以下の内容で登録しますか？</strong>
      </h1>
      <br>

      <%= form_with(model: @post, url: posts_path, local: true) do |form| %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :spot %>

      <% if @post.image.present? %>
        <%= image_tag(@post.image.url) %>
        <%= hidden_field_tag :"cache[image]",@post.image.cache_name %>
        <br>
      <% end %>

      <br>
      <br>

      <p class="lead">spot :
        <%= @post.spot %></p>
      <hr>

      <p class="lead">how about this spot? :
        <%= @post.content %></p>
      <hr>

      <br>
      <%= form.fields_for :wifis do |w| %>
      <%= w.hidden_field :condition_1 %>
      <%= w.hidden_field :condition_2 %>
      <%= w.hidden_field :condition_3 %>

      <h1>
        <i class="fa fas fa-wifi fa-fw fa-2x"></i>
        <strong>wifi情報</strong>
      </h1>
      <br>

      <% @post.wifis.each do |w| %>
        <p class="lead">事業者名 :
          <%= w.condition_1 %></p>
        <hr>
        <p class="lead">繋がりますか？ :
          <%= w.condition_2 %></p>
        <hr>
        <p class="lead">詳しい情報があれば... :
          <%= w.condition_3 %></p>
        <hr>
      <% end %>
    <% end %>

    <%= form.fields_for :toilets do |t| %>
    <%= t.hidden_field :information %>
    <%= t.hidden_field :comfortable %>
    <%= t.hidden_field :box_number %>
    <%= t.hidden_field :baggage %>

    <h1>
      <i class="fa fas fa-female fa-fw fa-2x"></i>
      <strong>toilet情報</strong>
    </h1>
    <br>

    <% @post.toilets.each do |t| %>

      <p class="lead">清潔ですか？ :
        <%= t.comfortable %></p>
      <hr>
      <p class="lead">個室はいくつありますか？ :
        <%= t.box_number %></p>
      <hr>
      <p class="lead">荷物置き場はありますか？ :
        <%= t.baggage %></p>
      <hr>
      <p class="lead">コメントがあれば... :
        <%= t.information %></p>
      <hr>

    <% end %>
  <% end %>

  <%= form.fields_for :troubles do |tr| %>
  <%= tr.hidden_field :atm %>
  <%= tr.hidden_field :station %>
  <%= tr.hidden_field :bus %>
  <%= tr.hidden_field :pharmacy %>

  <h1>
    <i class="fa fas fa-medkit fa-fw fa-2x"></i>
    <strong>help情報</strong>
  </h1>
  <br>

  <% @post.troubles.each do |tr| %>
    <p class="lead">近くのATMは？ :
      <%= tr.atm %></p>
    <hr>
    <p class="lead">一番近い駅は？ :
      <%= tr.station %></p>
    <hr>
    <p class="lead">一番近いバス停は？ :
      <%= tr.bus %></p>
    <hr>
    <p class="lead">近くにドラッグストアはある？ :
      <%= tr.pharmacy %></p>
    <hr>

  <% end %>
<% end %>

<%= form.submit "登録する" , class: 'col-xs-offset-4 col-xs-4 btn btn-danger btn-lg' %>
<% end %>

<br>
<%= form_with(model: @post, url: new_post_path, local: true, method: 'get') do |form| %>
<%= form.hidden_field :content %>
<%= form.hidden_field :spot %>

<%= form.fields_for :wifis do |w| %>
<%= w.hidden_field :condition_1 %>
<%= w.hidden_field :condition_2 %>
<%= w.hidden_field :condition_3 %>
<% end %>

<%= form.fields_for :toilets do |t| %>
<%= t.hidden_field :information %>
<%= t.hidden_field :comfortable %>
<%= t.hidden_field :box_number %>
<%= t.hidden_field :baggage %>
<% end %>

<%= form.fields_for :troubles do |tr| %>
<%= tr.hidden_field :atm %>
<%= tr.hidden_field :station %>
<%= tr.hidden_field :bus %>
<%= tr.hidden_field :pharmacy %>
<% end %>

<br>
<br>
<%= form.submit "戻る" ,name: 'back', class: 'col-xs-offset-4 col-xs-4 btn btn-dark btn-lg'%>
<% end %>

</div>
</div>
</div>
<hr>

app/views/posts/edit.html.erb
<aside class="callout">
  <div class="text-vertical-center">
    <h1>Are you edit?</h1>
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>編集画面</h2>
      </div>
    </div>
  </div>
</aside>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<aside class="callout">
    <div class="text-vertical-center">
        <h1>Index</h1>
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2>みんなの投稿をみる</h2>
          </div>
        </div>
    </div>
</aside>

<div class="container">
  <div class="row">

    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <h1>
          <i class="fa fas fa-search fa-fw fa-2x"></i>
          <strong>検索する</strong>
        </h1>
        <%= search_form_for @search do |f| %>
        <% if @search.present? %>
        <p class="lead"><%= @posts.count %>件見つかりました</p>
        <% end %>


          <p class="lead">行った場所を検索しよう</p>
          <div class="input-group">
            <%= f.text_field :spot_cont , class:"form-control" ,placeholder:"Search spot!" ,type:"text" %>
            <span class="input-group-btn">
            <%= f.submit 'Go',class:"btn btn-danger" ,type:"submit" %>
            </span>
          </div>

            <% if @posts.blank? %>
            <br>
            <p>お探しのspotは見つかりませんでした</p>
            <%= link_to '行った場所を登録しませんか？', new_post_path, class: 'btn btn-dark btn-lg'%>
            <% end %>
            <% end %>
        <br>
      <br>
      <br>
    </div>



    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <h1>
        <i class="fa fas fa-desktop fa-fw fa-2x"></i>
        <strong>投稿一覧</strong>
      </h1>
    </div>


    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-2">
      <br>
      <br>

      <div class="panel-group" id="sampleAccordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a data-toggle="collapse" data-parent="#sampleAccordion" href="#sampleAccordionCollapse2">
                <strong>click!</strong>
              </a>
            </h3>
          </div>

          <div id="sampleAccordionCollapse2" class="panel-collapse collapse">
            <div class="panel-body">

              <% @posts.each do |post| %>
                <p class="post-meta"><%= image_tag(post.user.image , size: 30) %>
                  <%= post.user.name %></p>
                <h2>
                  <i class="fa fas fas fa-map-marker fa-fw fa-1x"></i><%= post.spot %>
                </h2>
                <% if post.image.present? %>
                  <%= image_tag(post.image , size: 50) %>
                <% end %>
                <p class="post-meta">投稿日：<%= post.created_at.strftime("%Y-%m-%d%H:%M") %></p>
                <br>
                <% unless logged_in? %>
                <p class="post-meta">続きを見るにはログインが必要です</p>
                <%= link_to 'ログインする', post_path(post.id), class: 'btn btn-dark'%>
                <% else %>
                <%= link_to '続きを見る', post_path(post.id), class: 'btn btn-dark'%>
                <% end %>
                <hr>
                <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<aside class="callout">
  <div class="text-vertical-center">
    <h1>Let's show!</h1>
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>詳細</h2>
      </div>
    </div>
  </div>

</aside>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <% if current_user.id == @post.user.id %>
          <%= link_to '編集する', edit_post_path(@post.id), data: { confirm: '編集しますか？' }, class: 'btn btn-info btn-lg' %>
          <%= link_to '削除する', post_path(@post.id), method: :delete ,data: { confirm: '削除しますか？' } , class: 'btn btn-warning btn-lg'%>
        <% end %>
        <br>

        <% unless @post.user == current_user.id %>
          <% if @like.present? %>
            <br>
            <%= link_to 'お気に入りを取り消す',like_path(post_id: @post.id), method: :delete, class: 'btn btn-dark btn-lg' %>
            <hr>
          <% else %>
            <br>
            <%= link_to 'このspotをお気に入り登録する', likes_path(post_id: @post.id), method: :post, class: 'btn btn-danger btn-lg' %>
          <% end %>
        <% end %>
        <hr>

        <h1>
          <i class="fa fas fas fa-map-marker fa-fw fa-2x"></i>
          <strong><%= @post.spot %></strong>
        </h1>

        <br>
        <%= image_tag @post.image %>
        <br>
        <br>

        <p class="lead">how about this spot? :
          <%= @post.content %></p>
        <hr>
        <br>
        <h1>
          <i class="fa fas fa-wifi fa-fw fa-2x"></i>
          <strong>wifi情報</strong>
        </h1>
        <% @post.wifis.each do |w| %>
          <p class="lead">事業者名 :
            <%= w.condition_1 %></p><hr>
          <p class="lead">繋がりますか？ :
            <%= w.condition_2 %></p><hr>
          <p class="lead">詳しい情報があれば... :
            <%= w.condition_3 %></p><hr>
        <% end %>
        <br>

        <h1>
          <i class="fa fas fa-female fa-fw fa-2x"></i>
          <strong>toilet情報</strong>
        </h1>

        <% @post.toilets.each do |t| %>
          <p class="lead">清潔ですか？ :
            <%= t.comfortable %></p><hr>
          <p class="lead">個室はいくつありますか？ :
            <%= t.box_number %></p><hr>
          <p class="lead">荷物置き場はありますか？ :
            <%= t.baggage %></p><hr>
          <p class="lead">コメントがあれば... :
            <%= t.information %></p><hr>
        <% end %>
        <br>

        <h1>
          <i class="fa fas fa-medkit fa-fw fa-2x"></i>
          <strong>help情報</strong>
        </h1>

        <% @post.troubles.each do |tr| %>
          <p class="lead">近くのATMは？ :
            <%= tr.atm %></p><hr>
          <p class="lead">一番近い駅は？ :
            <%= tr.station %></p><hr>
          <p class="lead">一番近いバス停は？ :
            <%= tr.bus %></p><hr>
          <p class="lead">近くにドラッグストアはある？ :
            <%= tr.pharmacy %></p><hr>
        <% end %>
      </div>



      <div class="col-md-5 col-md-offset-7">
        <div class="panel-group" id="sampleAccordion">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">
                <a data-toggle="collapse" data-parent="#sampleAccordion" href="#sampleAccordionCollapse1">
                  <strong>コメント一覧</strong>
                </a>
              </h3>
            </div>

            <div id="sampleAccordionCollapse1" class="panel-collapse collapse in">
              <div class="panel-body">

                <div id="comments_area">

                  <%= render partial: 'comments/index', locals: { comments: @comments, post: @post } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

<br>

      <div class="col-md-5 col-md-offset-7">
        <p class="lead">
          <i class="fa far fa-comments fa-fw fa-1x"></i>
          <strong>このspotへコメントする</strong>
        </p>
      </div>

      <div class="form-group col-md-5 col-md-offset-7 floating-label-form-group controls">
        <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
      </div>

    </div>
  </div>
</article>

<hr>

app/views/users/show.html.erb
<aside class="callout">
    <div class="text-vertical-center">
        <h1>User Profile</h1>
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2><%= @user.name %>さん、こんにちは</h2>
            </div>
        </div>
    </div>
</aside>

<article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <h1><% if @user.image.present? %>
            <%= image_tag(@user.image.url) %>
          <% end %>
          <strong>  Profile of <%= @user.name %></strong></h1>

          <hr>
          <br>

          <p class="lead"><i class="fa far fa-envelope fa-fw fa-2x"></i>：<%= @user.email %></p>
          <p class="lead"><i class="fa fa-map-marker fa-fw fa-2x"></i>：<%= @user.area %></p>
          <p class="lead"><i class="fa fab fa-angellist fa-fw fa-2x"></i>：<%= @user.introduction %></p>

            <br>

            <%= link_to 'プロフィールを編集する', edit_user_path(@user.id), data: { confirm: '編集しますか？' }, class: 'btn btn-info btn-lg' %>
          <br>
          <br>

          <h1><i class="fa far fa-thumbs-up fa-fw fa-2x"></i><strong>お気に入りspot一覧</strong></h1>
          <hr>
          <br>


          <% @likes_posts.each do |like| %>

            <p class="lead"><%= image_tag(like.user.image , size: 30) %><%= like.user.name %></p>
            <p class="lead"><%= like.spot %></p>
            <span><%= link_to 'お気に入りを取り消す', post_path(like) , method: :delete,class: 'btn btn-dark btn-lg'%></span>
            <br>
            <hr>

          <% end %>


        </div>
      </div>
    </div>
  </article>