config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'sessions#top'

  resources :likes, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :contacts
  resources :users
  resources :posts do
    resources :comments

    collection do
    post :confirm
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :wifis
  has_many :toilets
  has_many :troubles


  accepts_nested_attributes_for :wifis
  accepts_nested_attributes_for :toilets
  accepts_nested_attributes_for :troubles


  validates :content, presence: true
  validates :content,length:{maximum:500}
  validates :spot, presence: true
  mount_uploader :image, ImageUploader
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :post,optional: true

end

app/models/trouble.rb
class Trouble < ApplicationRecord
  belongs_to :post,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, uniqueness: true
  validates :email, uniqueness: true
  mount_uploader :image, ImageUploader

end

app/models/wifi.rb
class Wifi < ApplicationRecord
  belongs_to :post,optional: true

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    if logged_in?
      @contact = Contact.new(name: current_user.name, email: current_user.email)
    else
      @contact = Contact.new
    end
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver_later
        format.html { redirect_to @contact, notice: '受付しました' }
        format.json { render :show, status: :created, location: @contact }

      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }

      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: '更新しました' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'お問い合わせを取り消しました' }
      format.json { head :no_content }
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]


def create
  like = current_user.likes.create(post_id: params[:post_id])
  redirect_to posts_path, notice: "お気に入りしました"
end


def destroy
  like = current_user.likes.find_by(post_id: params[:post_id]).destroy
  redirect_to post_path, notice: "お気に入りを取り消しました"
end

private

def logged_in_user
  unless current_user
    flash[:referer] = 'ログインしてください'
    render new_session_path
  end
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new,:edit,:show]

  def index
    @posts = Post.all
    @search = Post.search(params[:q])
    @posts = @search.result
  end

  def new
    if params[:back]
      @post = Post.new(post_params)

    else
      @post = Post.new
      @post.wifis.build
      @post.toilets.build
      @post.troubles.build
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        ContactMailer.post_mail(@post).deliver_later
        format.html { redirect_to @post, notice: '投稿しました' }
        format.json { render :show, status: :created, location: @post }

      else
        render 'new'
      end
    end

  end

  def show
    @comment = @post.comments.build
    @comments = @post.comments
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to posts_path, notice: '編集しました！'
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '削除しました！'
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    render :new if @post.invalid?
  end

  private

  def post_params
    params.require(:post).permit(
      :content,
      :user_id,
      :image,
      :cache,
      :image_cach,
      :spot,
      wifis_attributes: [:condition_1, :condition_2, :condition_3 ],
      toilets_attributes: [:information, :comfortable, :box_number, :baggage ],
      troubles_attributes: [:atm, :station, :bus, :pharmacy ]
    )
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def logged_in_user
    unless current_user
      flash[:referer] = 'ログインしてください'
      render new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録完了しました"
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @likes_posts = @user.like_posts
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
       redirect_to @user, notice: '編集しました！'
    else
      render 'edit'
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :image,
        :area,
        :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_posts_path

    elsif action_name == 'edit'
      post_path
    end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user) #userを渡す
    session[:user_id] = user.id
  end

  def current_user #ログイン中のuserがいる場合
    @current_user ||= User.find_by(id: session[:user_id]) #userが存在しない場合falseを返す
  end

  def logged_in? #ログインしていればtrueを返す
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/toilets_helper.rb
module ToiletsHelper
end

app/helpers/troubles_helper.rb
module TroublesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wifis_helper.rb
module WifisHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
<% if contact.errors.any? %>
  <div id="error_explanation">
    <div class="col-lg-12 text-center">
      <h2><%= contact.errors.count %>件のエラーがあります</h2>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  </div>
<% end %>



<div class="row control-group">
  <div class="form-group col-xs-offset-2 col-xs-8 floating-label-form-group controls">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" ,placeholder: "お名前" %>
    <br>
  </div>
</div>

<div class="row control-group">
  <div class="form-group col-xs-offset-2 col-xs-8 floating-label-form-group controls">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" ,placeholder:"メールアドレス" %>
    <br>
  </div>
</div>

<div class="row control-group">
  <div class="form-group col-xs-offset-2 col-xs-8 floating-label-form-group controls">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" ,placeholder: "お問い合わせ内容" %>
    <br>
  </div>
</div>


<%= form.submit "Send" ,class:"col-xs-offset-4 col-xs-4 bbtn btn-danger btn-lg" %>


<% end %>
</div>

app/views/contacts/new.html.erb
<aside class="callout">
    <div class="text-vertical-center">
        <h1>contact?</h1>
    </div>
</aside>

<div name="sentMessage" id="contactForm" novalidate="novalidate">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <p class="lead">当サイトに関するお問い合わせはこちらからお願いします</p>

  </div>
  <br>
  <%= render 'form', contact: @contact %>

<br><br>
</div>

app/views/contacts/show.html.erb
<aside class="callout">
  <div class="text-vertical-center">
    <h1>contact?</h1>
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>お問い合わせありがとうございました</h2>
      </div>
    </div>
  </div>
</aside>

<div name="sentMessage" id="contactForm" novalidate="novalidate">
  <p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 offset-2 text-center">
        <h3>
          <i class="fa far fa-share-square fa-fw fa-2x"></i>
          <strong>お問い合わせを受付しました</strong>
        </h3>
        <hr class="small">
        <div class="post-preview">

          <p class="lead">
            <i class="fa fas fa-user-circle fa-fw fa-2x"></i>：<%= @contact.name %></p>
          <p class="lead">
            <i class="fa far fa-envelope fa-fw fa-2x"></i>：<%= @contact.email %></p>
          <p class="lead">
            <i class="fa far fa-comment fa-fw fa-2x"></i>：<%= @contact.content %></p>

          <hr class="small">
          <p class="lead">回答までしばらくお待ちください</p>

          <%= link_to 'お問い合わせページへ戻る', new_contact_path , class: 'btn btn-dark btn-lg' %></h2>
        <br>
        <br>
      </div>
    </div>
  </div>
</div>
</div>