config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'sessions#top'

  resources :likes, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :contacts
  resources :users
  resources :posts do
    resources :comments

    collection do
    post :confirm
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :wifis
  has_many :toilets
  has_many :troubles


  accepts_nested_attributes_for :wifis
  accepts_nested_attributes_for :toilets
  accepts_nested_attributes_for :troubles


  validates :content, presence: true
  validates :content,length:{maximum:500}
  validates :spot, presence: true
  mount_uploader :image, ImageUploader
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :post,optional: true

end

app/models/trouble.rb
class Trouble < ApplicationRecord
  belongs_to :post,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, uniqueness: true
  validates :email, uniqueness: true
  mount_uploader :image, ImageUploader

end

app/models/wifi.rb
class Wifi < ApplicationRecord
  belongs_to :post,optional: true

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]


def create
  like = current_user.likes.create(post_id: params[:post_id])
  redirect_to posts_path, notice: "お気に入りしました"
end


def destroy
  like = current_user.likes.find_by(post_id: params[:post_id]).destroy
  redirect_to post_path, notice: "お気に入りを取り消しました"
end

private

def logged_in_user
  unless current_user
    flash[:referer] = 'ログインしてください'
    render new_session_path
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_posts_path

    elsif action_name == 'edit'
      post_path
    end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user) #userを渡す
    session[:user_id] = user.id
  end

  def current_user #ログイン中のuserがいる場合
    @current_user ||= User.find_by(id: session[:user_id]) #userが存在しない場合falseを返す
  end

  def logged_in? #ログインしていればtrueを返す
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/toilets_helper.rb
module ToiletsHelper
end

app/helpers/troubles_helper.rb
module TroublesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wifis_helper.rb
module WifisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>the travelers</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/stylish-portfolio.css" rel="stylesheet">

    <!-- <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=YOUR_API_KEY&callback=initMap"> </script> -->

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- This stylesheet contains specific styles for displaying the map on this page. Replace it with your own styles as described in the documentation: https://developers.google.com/maps/documentation/javascript/tutorial -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]> <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script> <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script> <![endif]-->
  </head>

  <body>
    <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle">
      <i class="fa fa-bars"></i>
    </a>
    <nav id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle">
          <i class="fa fa-times"></i>
        </a>
        <li class="sidebar-brand">
          <a href="/" onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();""">the traveler</a>
        </li>
        <li>
          <a href="/contacts/new" onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();""">サポート</a>
        </li>

        <% if logged_in? %>
          <li>
            <a href="/posts" onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();""">投稿一覧</a>
          </li>
          <li>
            <a href="/posts/new" onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();""">投稿する</a>
          </li>
          <li>
            <a onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();"""><%= link_to "プロフィール", user_path(current_user.id) %></a>
          </li>
          <li>
            <a onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();"""><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></a>
          </li>
        <% else %>
          <li>
            <a href="/sessions/new" onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();""">ログイン</a>
          </li>
          <li>
            <a href="/users/new" onclick="$(" #menu-close").click();"="#menu-close" ).click();""=").click();""">サインアップ</a>
          </li>
        <% end %>

      </ul>
    </nav>
    <div class="key">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </div>
    <%= yield %>
    <br>
    <br>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-10 col-lg-offset-1 text-right">
            <h4>
              <strong>the travelers</strong>
            </h4>
            <p>2019/02</p>
            <br>
            <ul class="list-inline">
              <% if logged_in? %>
                <li class="list-line">
                  <a>
                    <i class="fa fas fa-user-circle fa-fw fa-3x"></i>
                    <%= link_to "プロフィール", user_path(current_user.id) %>
                  </a>
                </li>

                <li class="list-line">
                  <a href="/posts/new">
                    <i class="fa fas fa-paste fa-fw fa-3x"></i>新規投稿
                  </a>
                </li>
                <br>
              <% end %>

              <li class="list-line">
                <a href="/posts">
                  <i class="fa fas fa-list fa-fw fa-3x"></i>投稿一覧
                </a>
              </li>

              <li class="list-line">
                <a href="/">
                  <i class="fa fa-dribbble fa-fw fa-3x"></i>トップへ戻る
                </a>
              </li>

            </ul>
            <p class="text-muted">Copyright &copy; the travelers 2018</p>
          </div>
        </div>
      </div>

      <a id="to-top" href="#top" class="btn btn-dark btn-lg">
        <i class="fa fa-chevron-up fa-fw fa-1x"></i>
      </a>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script>
      // Closes the sidebar menu
      $("#menu-close").click(function (e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
      });
      // Opens the sidebar menu
      $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
      });
      // Scrolls to the selected menu item on the page
      $(function () {
        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function () {
          if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
            var target = $(this.hash);
            target = target.length
              ? target
              : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
              $('html,body').animate({
                scrollTop: target.offset().top
              }, 1000);
              return false;
            }
          }
        });
      });
      //#to-top button appears after scrolling
      var fixed = false;
      $(document).scroll(function () {
        if ($(this).scrollTop() > 250) {
          if (!fixed) {
            fixed = true;
            // $('#to-top').css({position:'fixed', display:'block'});
            $('#to-top').show("slow", function () {
              $('#to-top').css({position: 'fixed', display: 'block'});
            });
          }
        } else {
          if (fixed) {
            fixed = false;
            $('#to-top').hide("slow", function () {
              $('#to-top').css({display: 'none'});
            });
          }
        }
      });
      // Disable Google Maps scrolling See http://stackoverflow.com/a/25904582/1607849 Disable scroll zooming and bind back the click event var onMapMouseleaveHandler = function (event) {   var that = $(this);   that.on('click', onMapClickHandler);
      // that.off('mouseleave', onMapMouseleaveHandler);   that.find('iframe').css("pointer-events", "none"); } var onMapClickHandler = function (event) {   var that = $(this);    Disable the click handler until the user leaves the map area
      // that.off('click', onMapClickHandler);    Enable scrolling zoom   that.find('iframe').css("pointer-events", "auto");    Handle the mouse leave event   that.on('mouseleave', onMapMouseleaveHandler); }  Enable map zooming with mouse scroll when the
      // user clicks the map $('.map').on('click', onMapClickHandler);
    </script>
  </body>
</html>